runtime: php55

handlers:

# Serve home page
- url: /
  script: index.php
  
# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve stylesheets
- url: /css
  static_dir: css
